<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models - The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="regression-challenge---linear-model-interpretability" class="level1">
<h1>Regression Challenge - Linear Model Interpretability</h1>
<section id="the-problem-when-controlling-for-goes-wrong" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-when-controlling-for-goes-wrong">The Problem: When “Controlling For” Goes Wrong</h2>
<blockquote class="blockquote">
<p>“We need to stop believing much of the empirical work we’ve been doing.” - Christopher H. Achen</p>
</blockquote>
<p><strong>What does “control for” mean?</strong> Imagine you’re studying whether social media causes anxiety. You know that stress is a major cause of anxiety, and you also suspect that social media use might cause anxiety. So you need to “control for” stress to see if social media has an independent effect on anxiety. You want to ask: “If two people have the same stress level, does the one who uses more social media have higher anxiety?”</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🎯 The Key Insight: Non-Linearity Breaks Even “Good” Regressions
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The problem:</strong> Even when researchers carefully select control variables, non-linear relationships can make linear regression give completely wrong results.</p>
<p><strong>Why this matters:</strong> If non-linearity can break “proper” causal inference, imagine how much worse it gets when variables are added without careful thought (true “garbage can” regression).</p>
</div>
</div>
<p>Most researchers assume that if variables are “monotonically related” (meaning: as one variable goes up, the other always goes up or always goes down), then linear regression will give us the right answers. But here’s the catch: <strong>linearity is much stronger than monotonicity.</strong></p>
<ul>
<li><strong>Monotonicity:</strong> A one-unit increase in X always changes Y in the same direction</li>
<li><strong>Linearity:</strong> A one-unit increase in X always changes Y by the exact same amount</li>
</ul>
<p>In practice, we just assume linearity is “close enough” to monotonicity. But what if it’s not? Your challenge is to explore a simple example and show how even small non-linearities can make regression results completely wrong.</p>
<section id="the-true-relationship" class="level3">
<h3 class="anchored" data-anchor-id="the-true-relationship">The True Relationship</h3>
<p>We define three variables:</p>
<p><span class="math display">\[
\begin{aligned}
A &amp;\equiv \textrm{Anxiety Level measured by fMRI activity}\\
S &amp;\equiv \textrm{Stress Level measured by cortisol level in blood}\\
T &amp;\equiv \textrm{\# of minutes on social media in last 24 hours}
\end{aligned}
\]</span></p>
<p>We <strong>know</strong> the true relationship among these variables:</p>
<p><span class="math display">\[
Anxiety = Stress + 0.1 \times Time
\]</span></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🔍 The True Coefficients
</div>
</div>
<div class="callout-body-container callout-body">
<p>This equation implies specific values in the multiple regression framework <span class="math inline">\(Anxiety = \beta_0 + \beta_1 \times Stress + \beta_2 \times Time + \epsilon\)</span>:</p>
<ul>
<li><span class="math inline">\(\beta_0 = 0\)</span> (intercept is zero)</li>
<li><span class="math inline">\(\beta_1 = 1\)</span> (coefficient on Stress is 1)</li>
<li><span class="math inline">\(\beta_2 = 0.1\)</span> (coefficient on Time is 0.1)</li>
</ul>
<p>When you run regression analysis, you’re trying to estimate these <span class="math inline">\(\beta\)</span> coefficients. If your regression gives coefficients very different from these true values, <strong>your model is wrong—even if it has good statistical fit!</strong> Keep these values handy as you answer every question below.</p>
</div>
</div>
</section>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<div class="cell" data-execution_count="2">
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Verify for yourself that <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span> holds perfectly in every row. Notice the additional <code>StressSurvey</code> column—a survey-based proxy for measuring stress levels without expensive blood tests. The proxy has a <em>monotonic</em> (and sorta-kinda <em>linear</em>) relationship with actual stress (see <a href="#fig-stress-proxy" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📝 Methodological Note: The Contrived Nature of This Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is a contrived example designed to illustrate the dangers of linear regression:</p>
<ul>
<li><strong>Blood test stress levels</strong> have a perfectly linear relationship with anxiety (by design)</li>
<li><strong>Survey stress responses</strong> have a non-linear relationship with anxiety (also by design)</li>
</ul>
<p>In the real world, there is no reason to believe linearity holds for either measurement method. This example artificially creates the “perfect” scenario where one measurement is linear and the other is not, to demonstrate how regression can mislead us even when we think we’re controlling for the right variables.</p>
</div>
</div>
<div id="cell-fig-stress-proxy" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-stress-proxy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-proxy-output-1.png" width="662" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: StressSurvey as a proxy for actual Stress levels
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="analysis-tasks" class="level2">
<h2 class="anchored" data-anchor-id="analysis-tasks">Analysis Tasks</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🎯 The Benchmark: True Coefficients
</div>
</div>
<div class="callout-body-container callout-body">
<p>For every regression you run below, compare your estimated coefficients to these true values:</p>
<ul>
<li><span class="math inline">\(\beta_0 = 0\)</span> (intercept) | <span class="math inline">\(\beta_1 = 1\)</span> (Stress) | <span class="math inline">\(\beta_2 = 0.1\)</span> (Time)</li>
</ul>
<p>Are your estimates close? If not, your model is telling a wrong story – even if R-squared is high and p-values are small.</p>
</div>
</div>
<ol type="1">
<li><strong>Bivariate Regression: Anxiety on StressSurvey.</strong> Run a bivariate regression of Anxiety on StressSurvey. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<ol type="1">
<li>Bivariate Regression: Anxiety on StressSurvey</li>
</ol>
<div id="1c09ffe2" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated coefficients:
Intercept: -1.524
Slope for StressSurvey: 1.047</code></pre>
</div>
</div>
<p>（2）Interpretation: ① From the bivariate regression of Anxiety on StressSurvey, we obtain the fitted line: Anxiety=-1.524+1.047* StressSurvey So the estimated coefficients are: Intercept=-1.524 ; Slope=1.047 ② The true data‑generating model is: Anxiety=1 * Stress+0.1 * Time. Our regression only uses ‘StressSurvey’, which is a noisy proxy for Stress and does not include ‘Time’ at all. Because of this, the estimated slope (1.047) and intercept (−1.524) do not match the true coefficients. The regression captures the observed pattern between StressSurvey and Anxiety, but it cannot recover the true causal effects from the underlying model.</p>
<ol start="2" type="1">
<li><strong>Visualization: StressSurvey vs Anxiety.</strong> Create a scatter plot with the regression line showing the relationship between StressSurvey and Anxiety. Comment on the fit and any potential issues. (1)Visualization: StressSurvey vs Anxiety.</li>
</ol>
<div id="ee8a19da" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-6-output-1.png" width="1142" height="396" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated coefficients:
Intercept (beta_0): -1.524
Slope for StressSurvey (beta_1): 1.047

Regression equation:
Anxiety_hat = -1.524 + 1.047 * StressSurvey</code></pre>
</div>
</div>
<p>(2)Interpretation: The regression of Anxiety on StressSurvey produces the fitted line: Anxiety = -1.524 + 1.047 * StressSurvey.</p>
<p>This line fits the left panel very well, showing a clear positive relationship between StressSurvey and Anxiety. However, this does not represent the true data‑generating process. In reality, Anxiety is determined by: Anxiety=1 * Stress+ 0.1 * Time, with a true intercept of 0. ‘StressSurvey’ is only a noisy proxy for Stress and contains no information about Time.</p>
<p>Therefore, the estimated slope 1.047 is not the true Stress coefficient (which is 1), and the intercept −1.524 is far from the true value 0. The fitted line matches the left plot visually, but its coefficients do not reflect the true causal effects.</p>
<p>(3)Analysis: The left panel shows that the fitted line -1.524+1.047* StressSurvey, aligns well with the observed Anxiety–StressSurvey scatterplot, indicating a good statistical fit for this bivariate regression.</p>
<p>But the other two panels reveal why this is misleading: Anxiety is actually driven by both Stress and Time, while the regression uses only StressSurvey. Because StressSurvey is an imperfect proxy for Stress and ignores Time completely, the model can look good visually but still produce biased coefficients.</p>
<p>So the regression fits the observed data well, but it does not recover the true underlying relationship.</p>
<ol start="3" type="1">
<li><strong>Bivariate Regression: Anxiety on Time.</strong> Run a bivariate regression of Anxiety on Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<ol type="1">
<li>Bivariate Regression: Anxiety on Time</li>
</ol>
<div id="6d08aab0" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>          Coefficient  Estimate
0  Intercept (beta_0) -3.680136
1       Time (beta_1)  5.340592
R-squared: 0.563039</code></pre>
</div>
</div>
<p>(2)Interpretation: ① From the bivariate regression of Anxiety on Time, we obtain the fitted line: Anxiety=-3.680 + 5.341<em>Time. So the estimated coefficients are: Intercept= −3.680 ; Slope for Time=5.341. ② The true data‑generating model is: Anxiety=1 </em> Stress+ 0.1 * Time. The bivariate regression we generate estimates a much larger slope (5.341 VS 1). This happens because the regression uses only Time and omits Stress, which is the main driver of Anxiety. Since Time is correlated with Stress in the simulated data, the regression incorrectly attributes part of Stress’s effect to Time. As a result, both the slope and intercept are far from the true values. The model captures an association between Time and Anxiety, but it does not reflect the true causal effect of Time in the underlying process.</p>
<ol start="4" type="1">
<li><strong>Visualization: Time vs Anxiety.</strong> Create a scatter plot with the regression line showing the relationship between Time and Anxiety. Comment on the fit and any potential issues. (1)Visualization: Time vs Anxiety</li>
</ol>
<div id="19cfc051" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-8-output-1.png" width="1142" height="396" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="1">
<li><p>Interpretation: From the visualization of Time vs Anxiety, the fitted line: -3.680 + 5.341 * Time, matches the scatterplot fairly well, showing a clear positive association between Time and Anxiety. However, this pattern does not reflect the true data‑generating process. In the underlying model, Anxiety is determined by both Stress and Time: Anxiety=1 * Stress+0.1 * Time. The estimated slope (5.341) is much larger than the true Time coefficient (0.1), and the intercept (−3.680) also deviates from the true value 0. The fitted line captures the observed correlation in the plot, but the coefficients do not represent the true causal effects.</p></li>
<li><p>Analysis: The plot shows that the fitted line aligns well with the Time–Anxiety data, suggesting a good statistical fit. However, this fit is misleading. Anxiety is jointly determined by Stress and Time, yet the regression includes only Time. Since Time is correlated with Stress in the data, the model incorrectly attributes part of Stress’s effect to Time. As a result, the coefficients are biased even though the line appears to fit the scatterplot well.</p></li>
</ol>
<ol start="5" type="1">
<li><strong>Multiple Regression: StressSurvey + Time.</strong> Run a multiple regression of Anxiety on both <strong>StressSurvey</strong> and Time. What are the estimated coefficients? How do they compare to the true coefficients?</li>
</ol>
<ol type="1">
<li>Multiple Regression: StressSurvey + Time</li>
</ol>
<div id="45bb439a" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>
=== Q5: Multiple Regression (Anxiety ~ StressSurvey + Time) ===
Estimated coefficients:
  - Intercept (beta_0): 0.588758
  - StressSurvey coefficient (beta_1): 1.426926
  - Time coefficient (beta_2): -2.779944
  - R-squared: 0.935005

Fitted equation:
  Anxiety_hat = 0.588758 + 1.426926 * StressSurvey + -2.779944 * Time

Comparison to true coefficients:
  - True intercept: 0.000
  - True stress coefficient is 1.000 on Stress (not on StressSurvey)
  - True Time coefficient: 0.100
  - Difference in intercept: +0.588758
  - Difference in Time coefficient: -2.879944
  - Note: beta_1 here is on StressSurvey, so it is not directly comparable to the true Stress coefficient (1.0).</code></pre>
</div>
</div>
<p>（2）Interpretation: ① From the multiple regression of Anxiety on StressSurvey and Time, we get: Anxiety=0.589+1.427 * StressSurvey - 2.780 * Time. So the estimated coefficients are: Intercept=0.589 ; StressSurvey coefficient=1.427 ; Time coefficient=−2.780 ② The true model is: Anxiety=1 * Stress+0.1 * Time. Because the regression uses ‘StressSurvey’ instead of true ‘Stress’, and because ‘Time’ is correlated with ‘Stress’ in the data, the model cannot recover the true causal parameters. The coefficient on ‘StressSurvey’ does not match the true Stress coefficient (1), and the estimated Time coefficient (−2.780) is far from the true value (0.1). Although the multiple regression fits the data well, the coefficients remain biased due to measurement error in ‘StressSurvey’ and omitted‑variable effects related to ‘Stress’.</p>
<ol start="6" type="1">
<li><strong>Multiple Regression: Stress + Time.</strong> Run a multiple regression of Anxiety on both <strong>Stress</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<ol type="1">
<li>Multiple Regression: Stress + Time</li>
</ol>
<div id="11963ebc" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>
=== Q6: Multiple Regression (Anxiety ~ Stress + Time) ===
Estimated coefficients:
  - Intercept (beta_0): -0.0000000000
  - Stress coefficient (beta_1): 1.0000000000
  - Time coefficient (beta_2): 0.1000000000
  - R-squared: 1.0000000000

Fitted equation:
  Anxiety_hat = -0.0000000000 + 1.0000000000 * Stress + 0.1000000000 * Time

Comparison to true relationship (Anxiety = Stress + 0.1 * Time):
  - True intercept: 0.0 | Estimated: -0.0000000000 | Difference: -0.0000000000
  - True Stress coef: 1.0 | Estimated: 1.0000000000 | Difference: +0.0000000000
  - True Time coef: 0.1 | Estimated: 0.1000000000 | Difference: -0.0000000000</code></pre>
</div>
</div>
<p>（2）Interpretation: ① From the multiple regression of Anxiety on ‘Stress’ and ‘Time’, we obtain the fitted model: Anxiety=0+1 * Stress + 0.1 * Time So the estimated coefficients are: Intercept=approximately 0 ; Stress coefficient=1 ; Time coefficient=0.1 The R^2 is essentially 1.000, indicating an almost perfect fit. ② The true model is: Anxiety=1 * Stress+0.1 * Time. In this specification, the regression uses exactly the same predictors as the true model (Stress and Time), rather than a noisy proxy like ‘StressSurvey’. As a result, the estimated coefficients match the true parameters almost exactly. This shows that when we include the correct variables and the model is correctly specified, OLS can fully recover the true causal relationship.</p>
<ol start="7" type="1">
<li><strong>Model Comparison.</strong> Compare the R-squared values and coefficient interpretations between the two multiple regression models (Questions 5 and 6). Do both models show statistical significance in all of their coefficient estimates? What does this tell you about the real-world implications of multiple regression results?</li>
</ol>
<ol type="1">
<li><p>Comparison of R-squared and coefficients The multiple regression using ‘StressSurvey’ + ‘Time’ (Q5) achieves an R^2 of about 0.935, while the regression using the true predictors ‘Stress’ + ‘Time’ (Q6) achieves an R^2 of essentially 1.000. This difference reflects model specification that the Q6 model uses the exact variables from the true data generating process, so it fits almost perfectly. In contrast, the Q5 model replaces Stress with ‘StressSurvey’, which is a noisy proxy, leading to a lower R^2 and biased coefficient estimates. The coefficients also differ sharply. In Q6, the estimated coefficients match the true values almost exactly (Stress = 1, Time = 0.1). In Q5, the coefficient on ‘StressSurvey’ does not equal the true ‘Stress’ coefficient, and the ‘Time’ coefficient is strongly distorted because ‘StressSurvey’ does not fully capture the variation in Stress.</p></li>
<li><p>Statistical significance and real world implications Both models would likely show statistically significant coefficients because the predictors are correlated with Anxiety. However, significance alone does not guarantee that the coefficients represent true causal effects. Q5 demonstrates this clearly: even with a high R^2 and significant coefficients, the estimates are biased because the model uses an imperfect proxy and omits the true Stress variable. Q6 shows that only when the correct variables are included can the regression recover the true causal relationship. In real world applications, this shows an important point: a regression model can look “good” on paper, with high R^2, significant coefficients, yet still be wrong about the underlying causal effects if key variables are missing or measured poorly. Good statistical results do not automatically guarantee correct causal interpretation.</p></li>
</ol>
<ol start="8" type="1">
<li><strong>Real-World Implications.</strong> For each of the two multiple regression models, assume their outputs were published in academic journals and then picked up by the popular press. What headline about time spent on social media and its effect on anxiety would you expect from a press outlet covering the first model? What headline for the second model? Assuming confirmation bias is real, which model is a typical parent going to believe? Which model will Facebook, Instagram, and TikTok executives prefer?</li>
</ol>
<ol type="1">
<li>Model 1 headline: “Social media time strongly increases anxiety!”</li>
<li>Model 2 headline: “No more worries! Social media time has only a small effect on anxiety.”</li>
<li>Parents believe: Model 1 (fits their fears that social media is harming their children).</li>
<li>Executives prefer: Model 2 (protects their business and reduces public pressure for regulation).</li>
</ol>
<ol start="9" type="1">
<li><strong>Avoiding Misleading Statistical Significance.</strong> Reflect on this tip: split the sample into meaningful subsets (“statistical regimes”) and use graphical diagnostics for linearity rather than blind reliance on “canned” regressions. Apply this approach to the multiple regression of Anxiety on both StressSurvey and Time by analyzing a smartly chosen subset of the data. What specific subset did you choose and why? Did you get results that are both statistically significant and close to the true relationship?</li>
</ol>
<ol type="1">
<li><p>Subset: To apply the idea of “statistical regimes,” I selected a subset of the data where ‘StressSurvey’ is most accurate as a proxy for Stress. Specifically, I restricted the sample to the middle portion of the StressSurvey distribution (for example, the 30–70% quantile range), where the proxy error is smallest (according to the visualization before). This subset is meaningful because the main source of bias in the full-sample regression is measurement error in StressSurvey. By focusing on a region where the proxy is relatively reliable, we can better evaluate whether the regression recovers the true relationship.</p></li>
<li><p>Visualization</p></li>
</ol>
<div id="7f585ab6" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-11-output-1.png" width="1142" height="419" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== Subset Regression Summary ===
Subset rule: 30th-70th percentile of StressSurvey
StressSurvey quantile bounds: [3.000, 9.000]
Subset size: 9 / 15

OLS in subset: Anxiety ~ StressSurvey
Intercept (beta_0): -3.268889
Slope on StressSurvey (beta_1): 1.183889
R-squared: 0.862937

Fitted equation:
Anxiety_hat = -3.268889 + 1.183889 * StressSurvey</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Interpretation ① My visualization highlights the middle 30th–70th percentile of ‘StressSurvey’, where the proxy is most accurate. In the first panel, the subset points form a much cleaner, more linear relationship between ‘StressSurvey’ and ‘Anxiety’, compared to the full sample. The fitted regression line aligns closely with the subset points, and the noise seen in the full dataset is greatly reduced. The second and third panels show how this subset corresponds to more stable ranges of ‘Stress’ and ‘Time’, reinforcing that this region of the data behaves more consistently and is less affected by measurement error. Overall, the plots visually confirm that the subset behaves more like a “true” statistical regime where linearity holds better. ② I think this subset regression produces results that are both statistically meaningful and noticeably closer to the true relationship than the full-sample model in Question 5. The slope estimate in this subset is 1.184, which is much closer to the true Stress coefficient of 1.0 than the biased full-sample estimate. The intercept is still imperfect, but the overall fit is strong, with an R^2 of 0.863, indicating that the subset captures most of the true linear pattern. The improvement occurs because the subset reduces measurement error in ‘StressSurvey’, making it a more reliable proxy for Stress. This demonstrates that the misleading coefficients in the full sample were driven by noisy regions of the data. By focusing on a more stable statistical regime, the regression becomes more trustworthy and aligns more closely with the true data generating process.</li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>